export const INDIAN_BANKS = [
  // Public Sector Banks
  "State Bank of India (SBI)",
  "Punjab National Bank (PNB)",
  "Bank of Baroda",
  "Canara Bank",
  "Union Bank of India",
  "Bank of India",
  "Indian Bank",
  "Central Bank of India",
  "Indian Overseas Bank",
  "UCO Bank",
  "Bank of Maharashtra",
  "Punjab & Sind Bank",

  // Private Sector Banks
  "HDFC Bank",
  "ICICI Bank",
  "Axis Bank",
  "Kotak Mahindra Bank",
  "IndusInd Bank",
  "Yes Bank",
  "IDFC First Bank",
  "Federal Bank",
  "RBL Bank",
  "South Indian Bank",
  "Karur Vysya Bank",
  "Tamilnad Mercantile Bank",
  "City Union Bank",
  "Dhanlaxmi Bank",
  "Karnataka Bank",
  "Lakshmi Vilas Bank",
  "Nainital Bank",

  // Foreign Banks
  "Citibank",
  "HSBC",
  "Standard Chartered Bank",
  "Deutsche Bank",
  "Barclays Bank",
  "American Express",
  "Bank of America",

  // Small Finance Banks
  "AU Small Finance Bank",
  "Equitas Small Finance Bank",
  "Ujjivan Small Finance Bank",
  "Jana Small Finance Bank",
  "Suryoday Small Finance Bank",
  "Utkarsh Small Finance Bank",
  "ESAF Small Finance Bank",
  "Fincare Small Finance Bank",
  "North East Small Finance Bank",
  "Capital Small Finance Bank",
  "Unity Small Finance Bank",

  // Payment Banks
  "Paytm Payments Bank",
  "Airtel Payments Bank",
  "India Post Payments Bank",
  "Fino Payments Bank",
  "Jio Payments Bank",

  // NBFCs and Other Financial Institutions
  "Bajaj Finance",
  "Tata Capital",
  "Mahindra Finance",
  "L&T Finance",
  "Muthoot Finance",
  "Manappuram Finance",
  "Cholamandalam Investment and Finance",
  "Shriram Finance",
  "IIFL Finance",
  "Aditya Birla Finance",
  "HDB Financial Services",
  "Hero FinCorp",
  "Fullerton India",
  "ICICI Home Finance",
  "LIC Housing Finance",
  "HDFC Limited",
  "Indiabulls Housing Finance",
  "PNB Housing Finance",
  "Repco Home Finance",
  "Can Fin Homes",

  "Other",
] as const

export type BankName = typeof INDIAN_BANKS[number]
